/*
* generated by Xtext
*/
package org.axdt.as3.ui.outline;

import org.eclipse.xtext.ui.editor.outline.actions.DefaultContentOutlineNodeAdapterFactory;

public class As3OutlineNodeAdapterFactory extends DefaultContentOutlineNodeAdapterFactory {

	@SuppressWarnings("rawtypes")
	private static final Class[] types = { 
		// provide list of classes to adapt to, e.g.:
		// Entity.class
		// Service.class
	};

	@SuppressWarnings("rawtypes")
	@Override
	public Class[] getAdapterList() {
		return types;
	}

}

