/*
* generated by Xtext
*/
package org.axdt.as3.ui.contentassist;

import org.axdt.as3.ui.contentassist.AbstractAs3ProposalProvider;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class As3ProposalProvider extends AbstractAs3ProposalProvider {
	@Override
	public void completeKeyword(Keyword keyword, ContentAssistContext contentAssistContext, ICompletionProposalAcceptor acceptor) {
		//skip keywords
		if (Character.isLetter(keyword.getValue().charAt(0)))
			super.completeKeyword(keyword, contentAssistContext, acceptor);
	}
}
